name: flutter_rimo2
description: Rick And Mory information and chat bot app with go_router
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  df_repository:
    path: packages/df_repository
  entities_repository:
    path: packages/entities_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  go_router: ^3.0.7
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.9

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/
