name: rimo_api
description: The interface and models for an API providing access to backend.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.8
  coverage: ^1.1.0
  http_mock_adapter: ^0.3.2
  json_serializable: ^6.1.5
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
dependencies:
  dio: ^4.0.4
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  json_annotation: ^4.4.0

